jupytercalpoly/Jupyter-Bifrost

docs/PRESS_RELEASE.md

Formatted the press release in markdown and added it to the `/docs` folder.

Added Press Release

---

bifrost_jupyter_extension/bifrost.py
src/components/BifrostReactWidget.tsx
src/components/Onboarding/ChartChooser.tsx
src/components/Onboarding/ColumnScreen.tsx
src/components/Onboarding/OnboardingWidget.tsx
src/hooks/bifrost-model.ts
src/widget.ts

* Removed action menu in `chart chooser`.
* Fixed a bug that the given column is not automatically selected in `select column`.
* Fixed the bug where it throws an error when x/y and color columns are given.
* Made the variables passed as arguments to plot function are not unchangeable in select columns.
* The reasoning behind this is that the user can do many things such as the user can unclick the given x or y variables, see suggested graphs, and go back to select the given x or y variable which is really error-prone.
* Plot bifrost plot with x or y argument and a color argument.
* See the checkboxes are not clickable.
* See that there is no errors in suggesting possible graphs.

Few changes in onboarding UI

---

bifrost_jupyter_extension/bifrost.py
examples/introduction.ipynb
src/components/BifrostReactWidget.tsx
src/components/Graph.tsx
src/components/Onboarding/ChartChooser.tsx
src/components/Onboarding/ColumnScreen.tsx
src/components/Onboarding/OnboardingWidget.tsx
src/components/Sidebar/Sidebar.tsx
src/components/Sidebar/Tabs/CustomizationTab/CustomizationTab.tsx
src/components/Sidebar/Tabs/CustomizationTab/MarkSubTab.tsx
src/components/Sidebar/Tabs/FilterScreen.tsx
src/components/Sidebar/Tabs/HistoryTab.tsx
src/components/Sidebar/Tabs/VariablesTab.tsx
src/components/VisualizationScreen.tsx
src/components/ui-widgets/RangeSlider.tsx
src/hooks/bifrost-model.ts
src/modules/VegaPandasTranslator.ts
src/widget.ts

**Adds a better UI component to deal with filtering along quantitative ranges**
1. Open filters on a quantitative encoded variable.
2. Change the min and max by pulling the handles on the slider
3. Change the min and max by changing the inputs to each side of the slider and hitting Enter
4. Hover over the slider track and see the value being displayed
5. Click on the track and verify that the nearest bound jumps to the position.
6. Add a filter and ensure that the final range is the combination of the ranges of the two filters.
7. Delete both filters and add once back. Ensure that it still works
8. Export code and ensure that the result runs correctly.

Range Slider

---

.husky/pre-commit
bifrost_jupyter_extension/bifrost.py
examples/introduction.ipynb
src/__tests__/VegaPandasTranslator.spec.ts
src/__tests__/index.spec.ts
src/__tests__/mocks/compassql.ts
src/assets/icons/BarChartIcon.tsx
src/assets/icons/Icon.d.ts
src/assets/icons/LineChartIcon.tsx
src/assets/icons/PieChartIcon.tsx
src/assets/icons/ScatterChartIcon.tsx
src/components/BifrostReactWidget.tsx
src/components/Onboarding/ChartChooser.tsx
src/components/Onboarding/ChartFilter.tsx
src/components/Onboarding/ColumnSelectorSidebar.tsx
src/components/Onboarding/KeyboardNav.tsx
src/components/Onboarding/OnboardingWidget.tsx
src/components/VisualizationScreen.tsx
src/components/ui-widgets/Pill.tsx
src/components/ui-widgets/SearchBar.tsx
src/custom.d.ts
src/widget.ts
webpack.config.js
yarn.lock

Combines the `ColumnScreen` and `ChartChooser` into a single `OnboardingWidget`.

Updated Onboarding

---

examples/introduction.ipynb
src/components/Graph.tsx
src/components/Sidebar/Tabs/FilterScreen.tsx
src/components/ui-widgets/RangeSlider.tsx

**Axis sliders now save to spec history: Fixes #67 **
- A new entry is added to history when the user releases the slider.
Testing
- Mess with the sliders in the GUI and verify that a new entry is saved to history when the user finishes their slide.

Axis Slider History

---

.husky/pre-commit
bifrost_jupyter_extension/__init__.py
bifrost_jupyter_extension/bifrost.py
jest.config.js
package.json
src/__tests__/mocks/draco-core.ts
src/assets/icons/TickChartIcon.tsx
src/components/Onboarding/ChartChooser.tsx
src/components/Onboarding/ChartFilter.tsx
src/components/Onboarding/ColumnSelectorSidebar.tsx
src/components/Sidebar/Sidebar.tsx
src/widget.ts

* Replaced compassQL with Draco for graph recommendation
* Since Draco doesn't accept space or parenthesis for field name, created a method to handle this.
* Space will be replaced with underscore
* Parenthesis will be removed 
* Plot bifrost
* See recommended graphs on onboarding

Replace compassQL with Draco

---

src/components/Graph.tsx
src/components/Onboarding/ChartChooser.tsx
src/components/Onboarding/ColumnSelectorSidebar.tsx
src/components/Sidebar/Sidebar.tsx
src/components/VisualizationScreen.tsx

Fixed some minor bugs. #84 #85 #86 #87

Minor bugs

---

bifrost_jupyter_extension/bifrost.py
examples/introduction.ipynb
src/assets/icons/TickChartIcon.tsx
src/components/BifrostReactWidget.tsx
src/components/Onboarding/ChartChooser.tsx
src/components/Onboarding/ChartFilter.tsx
src/components/Onboarding/ColumnSelectorSidebar.tsx
src/components/Onboarding/OnboardingWidget.tsx
src/components/Sidebar/Sidebar.tsx
src/components/Sidebar/Tabs/CustomizationTab/CustomizationTab.tsx
src/components/Sidebar/Tabs/CustomizationTab/MarkSubTab.tsx
src/components/Sidebar/Tabs/DataTab.tsx
src/components/Sidebar/Tabs/FilterScreen.tsx
src/components/Sidebar/Tabs/HistoryTab.tsx
src/components/Sidebar/Tabs/MarkTab.tsx
src/components/VisualizationScreen.tsx
src/modules/VegaEncodings.ts
src/modules/VegaFilters.ts

- Fixed chart sizing in ChartChooser.
- Chart column selector now scrolls.
- Sidebar has minimum height so it doesn't get squished vertically in small screen widths when forced to the next line.
- Sidebar contents is set relative to the `.sidebar-content` class which fixes the majority of the sizing issues of the individual tabs.
- Columns are alphabetized.
- User can no longer open Filter Screen when field isn't chosen.

Fixed Size/Styling issues

---

examples/introduction.ipynb
src/components/Sidebar/Tabs/DataTab.tsx
src/components/Sidebar/Tabs/FilterScreen.tsx
src/components/ui-widgets/GraphPill.tsx

You can toggle the type of pills between `nominal` and `quantitative`
1. Plot survived vs some quantitative variable.
2. Click on the type icon in the survived pill.
3. Verify that the type icon changes to nominal and the graph updates accordingly.

Pill type toggle

---

examples/introduction.ipynb
package.json
src/components/HelpScreen/HelpScreen.tsx
src/components/HelpScreen/articles.ts
src/components/NavBar.tsx
src/components/Onboarding/ChartChooser.tsx
src/components/VisualizationScreen.tsx
yarn.lock

Added Help Screens to the Onboarding Screen and Visualization Screen.
- Brought in `react-markdown` to render help articles
- Added `HelpScreen` widget
1. Open the help screen using the help icon button in the Onboarding Screen and Visualization Screen.
2. For each make sure that the links function and clicking on the backdrop dismisses the popup.

Help Screen

---

src/components/Sidebar/Sidebar.tsx

Updated Sidebar

---

docs/source/_static/embed-bundle.js.LICENSE.txt
src/components/Onboarding/ChartChooser.tsx
src/components/Onboarding/ChartFilter.tsx
src/components/Tooltip.tsx

- Filters are mutually exclusive and appear grayed out at first
- Filter icons have tooltip indicators
- New general purpose `Tooltip` component
- Updated message in `ChartChooser`
- Verify that clicking a filter will restrict graphs to only that type.
- Verify that all graphs are shown with no filters applied.
- Verify that the default state is to show all graphs.

Chart Chooser Updates

---

src/components/Sidebar/Tabs/NearByTab.tsx

* Excluded facetted graphs from nearby.
* If the main graph itself is facetted, then nearby tab doesn't recommend any.

Exclude facetted graphs 

---

src/components/Tooltip.tsx

Quick style improvements to tooltip. Also made tooltips non interactive so they don't stick around on hover.
https://user-images.githubusercontent.com/33008436/129973567-346f9b3d-75df-4686-8ae7-a16433f816d3.mov

Tooltip Style Edits

---

src/components/Sidebar/Tabs/HistoryTab.tsx

* Really really minor history style change

History style

---

src/assets/icons/filterIcons/FilterIconMap.ts
src/assets/icons/filterIcons/FilterSliderIcon.tsx
src/assets/icons/filterIcons/ScaleIcon.tsx
src/components/ui-widgets/GraphPill.tsx
src/theme.ts

* Reflect the graph pill design on figma

Minor graphPill Design update

---

src/components/Graph.tsx
src/components/HelpScreen/HelpScreen.tsx
src/components/NavBar.tsx
src/components/Sidebar/Tabs/EditTab.tsx
src/components/VisualizationScreen.tsx
src/components/ui-widgets/Modal.tsx
src/components/ui-widgets/MoreMenu.tsx

https://user-images.githubusercontent.com/33008436/130107216-44fdd0d2-c870-4c72-8ba3-2af6b981fe17.mov
- Added new `Modal` component to deal with overlays like the `HelpScreen` and the `MoreMenu`
- Added an export menu that can export pngs, svgs and code
- Export a chart in different formats
- Change the chart and export it. Ensure that the chart actually changes.
> Note: Code export still doesn't work on this branch, but the logic should hold once we merge the fix.

Export Menu

---

src/components/Graph.tsx
src/components/ui-widgets/GraphPill.tsx

Fix #83
* Slider only opens for quantitative variable. For qualitative variable, it won't open the filter menu in the side bar as it isn't really necessary.
* Clicking axis will open the drop down for field in side bar to change it

Fixed axis slider issue

---

jupyter_bifrost/bifrost.py
src/components/Sidebar/Tabs/FilterScreen.tsx
src/components/ui-widgets/RangeSlider.tsx
src/modules/utils.ts

- Fixed Slider width
- Fixed slider typing
- Fixed title sizing for the filter screen with large titles
- Fixed sampling error in `bifrost.py`

Round 1 on Bugs 3

---

examples/introduction.ipynb
src/components/Sidebar/Tabs/AddPillScreen.tsx
src/components/Sidebar/Tabs/EditTab.tsx
src/modules/VegaEncodings.ts

Fixes #101
- Fix boxplot crash
- Enforced all vega marks for the `vegaMarkEncodingMap`
- Fixed associated type errors
See #101

Box and whisker bug

---

examples/introduction.ipynb
src/modules/VegaEncodings.ts
src/modules/VegaPandasTranslator.ts

Fixes #75 
- Try each axis scaling and verify that a new column appears in the output DataFrame.
- Try binning and verify that each index now has a bin interval as a new column.
> Note: if you mess with aggregation at all, you'll likely hit the bug addressed in #141

Scaling and Binning Pandas code

---

src/components/Onboarding/ColumnSelectorSidebar.tsx
src/components/Sidebar/Tabs/EditTab.tsx
src/components/Sidebar/Tabs/FilterScreen.tsx
src/components/ui-widgets/Slider.tsx

Last fixes

---

babel.config.js
src/__tests__/VegaPandasTranslator.spec.ts
src/__tests__/index.spec.ts
src/components/Sidebar/Tabs/CustomizationTab/CustomizationTab.tsx

Just commented out the index.spec.ts which causes issue with esmodules.
Need to set up the Jest config to handle esmodule

Fix build error

---

PRESS_RELEASE.md
babel.config.js
jupyter_bifrost/_frontend.py
jupyter_bifrost/_version.py
package.json
src/__tests__/VegaPandasTranslator.spec.ts
src/__tests__/index.spec.ts
src/components/Sidebar/Tabs/CustomizationTab/CustomizationTab.tsx

Added press release.
Updated version to 0.3.0

Press release & Version update
